In [3]:
#for tensorflow installation on machine
#https://www.youtube.com/watch?v=5Ym-dOS9ssA&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb

In [43]:
# import os
# os.environ ['TF_CPP_MIN_LOG_LEVEL' ] = '2' it is for local machine
import tensorflow as tf
# physical_devices = tf.config. list_physical_devices ('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[o], True)

In [9]:
tf.__version__

'2.15.0'

In [21]:
# Initialization of Tensors

x=tf.constant(4)
print(x)
x=tf.constant([1,2,3,4,5])
print(x)
x = tf.constant (4, shape= (1,1), dtype=tf.float32)
print(x)
x = tf.constant([[1,2,3], [4,5,6]])
print(x)
x = tf.ones( (3,3))
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [25]:
x = tf .zeros ((2, 3))
print(x)
x = tf.eye (3) # I for the identity matrix (eye)
print(x)
#for normal distribution
x = tf.random. normal ( (3, 3), mean=0, stddev=1)
print(x)
x = tf .random. uniform ((1,3), minval=0, maxval=1)
print(x)
x = tf.range (start=1, limit=5, delta=0.2)
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.45626366 -0.46025705 -0.23991731]
 [ 0.02598654 -0.8076121   0.05979083]
 [-1.1291066   1.1416863  -0.84317046]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.66870415 0.46985793 0.3433901 ]], shape=(1, 3), dtype=float32)
tf.Tensor(
[1.        1.2       1.4       1.6       1.8       2.        2.2
 2.4       2.6       2.8000002 3.        3.2       3.4       3.6000001
 3.8       4.        4.2       4.4       4.6000004 4.8      ], shape=(20,), dtype=float32)


In [28]:
#for converting float32 to 64 or to int or to bool
x = tf. cast (x, dtype=tf. float64)
print(x)
# tf.float (16, 32,64), tf.int (8, 16, 32, 64), tf .bool

tf.Tensor([1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4.], shape=(20,), dtype=float64)


In [48]:
# Mathematical Operations
x = tf.constant ([1,2,3])
y = tf. constant ([9,8, 7])
z = tf.add(x, y)
print(z)
z = x + y
print(z)

z = tf.subtract(x, y)
print(z)
z = x - y
print(z)

z = tf.multiply(x, y)
print(z)
z = x * y
print(z)

z = tf.divide(x, y)
print(z)
z = x / y
print(z)

#for dot product
z=tf.tensordot(x,y,axes=1)
print(z)
z=tf.reduce_sum(x*y,axis=0)
print(z)

z=x**5
print(z)

#matrix multiply
x = tf.random. normal ((2, 3))
y = tf .random. normal ((3, 4))
z = tf. matmul(x, y)
print (z)
z = x @ y
print (z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-1.0516622   1.9677544  -0.5262141  -0.98212224]
 [-1.3551259   0.87477225 -1.4450108  -1.6159738 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.0516622   1.9677544  -0.5262141  -0.98212224]
 [-1.3551259   0.87477225 -1.4450108  -1.6159738 ]], shape=(2, 4), dtype=float32)


In [54]:
#indexing

x = tf. constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:1])
print(x[1:3])
print (x[::2])
print(x[::-1])

#for getting perticular indices values
indices = tf .constant([0, 3])
x_ind = tf. gather(x, indices)
print (x_ind)

x = tf. constant([[1, 2],
[3, 4],
[5, 6]])
print (x[0,:])
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [59]:
#reshaping

x = tf.range(9)
print(x)
x = tf.reshape(x, (3,3))
print(x)
x = tf. transpose (x, perm= [1,0])#perm is for telling which axis to swap as it is tensor so here 1 and 0
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
